
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/database.types';

const SUPABASE_URL = "https://viteepgzfcqtrjanlbni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpdGVlcGd6ZmNxdHJqYW5sYm5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTQwNzMsImV4cCI6MjA2MDgzMDA3M30.UxDsWwDT5JJt-qi-JQbfqKC5PNH-tl9DqOiDU_Nozyk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
